# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{web-app-theme}
  s.version = "0.5.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrea Franz"]
  s.date = %q{2010-01-11}
  s.description = %q{Web app theme generator for rails projects}
  s.email = %q{andrea@gravityblast.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "config/locales/de_de.yml",
     "config/locales/pt_br.yml",
     "features/step_definitions/layout_steps.rb",
     "features/step_definitions/themed_steps.rb",
     "features/support/env.rb",
     "features/theme_generator.feature",
     "features/themed_generator.feature",
     "images/avatar.png",
     "images/icons/application_edit.png",
     "images/icons/cross.png",
     "images/icons/key.png",
     "images/icons/tick.png",
     "index.html",
     "javascripts/jquery-1.3.min.js",
     "javascripts/jquery.localscroll.js",
     "javascripts/jquery.scrollTo.js",
     "lib/web_app_theme.rb",
     "rails_generators/theme/USAGE",
     "rails_generators/theme/templates/view_layout_administration.html.erb",
     "rails_generators/theme/templates/view_layout_sign.html.erb",
     "rails_generators/theme/templates/web_app_theme_override.css",
     "rails_generators/theme/theme_generator.rb",
     "rails_generators/themed/USAGE",
     "rails_generators/themed/templates/view_edit.html.erb",
     "rails_generators/themed/templates/view_form.html.erb",
     "rails_generators/themed/templates/view_new.html.erb",
     "rails_generators/themed/templates/view_show.html.erb",
     "rails_generators/themed/templates/view_sidebar.html.erb",
     "rails_generators/themed/templates/view_signin.html.erb",
     "rails_generators/themed/templates/view_signup.html.erb",
     "rails_generators/themed/templates/view_tables.html.erb",
     "rails_generators/themed/templates/view_text.html.erb",
     "rails_generators/themed/themed_generator.rb",
     "stylesheets/base.css",
     "stylesheets/themes/bec-green/style.css",
     "stylesheets/themes/bec/style.css",
     "stylesheets/themes/blue/style.css",
     "stylesheets/themes/default/style.css",
     "stylesheets/themes/djime-cerulean/style.css",
     "stylesheets/themes/drastic-dark/style.css",
     "stylesheets/themes/kathleene/style.css",
     "stylesheets/themes/olive/style.css",
     "stylesheets/themes/orange/style.css",
     "stylesheets/themes/reidb-greenish/style.css",
     "stylesheets/themes/warehouse/style.css",
     "test/spec_helper.rb",
     "test/themed_generator_spec.rb",
     "web-app-theme.gemspec"
  ]
  s.homepage = %q{http://github.com/pilu/web-app-theme}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Web app theme generator}
  s.test_files = [
    "test/spec_helper.rb",
     "test/themed_generator_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

